# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0006_fbuser_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_mcbot.FBUser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_mcbot.StudentSociety')),
                ('event_time', models.DateField(null=True)),
            ],
        ),
    ]
