# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0007_studentsociety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('engineering', 'Engineering')], default='engineering', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('architecture', 'Architecture'), ('bioengineering', 'Bioengineering'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('computer_engineering', 'Computer Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('materials_engineering', 'Materials Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('mining_engineering', 'Mining Engineering'), ('software_engineering', 'Software Engineering')], default='architecture', max_length=70)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_mcbot.Faculty')),
            ],
        ),
    ]
