# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0007_studentsociety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_mcbot.FBUser')),
            ],
        ),
    ]
