# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0008_faculty_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('science', 'Science'), ('arts', 'Arts'), ('education', 'Education')], default='engineering', max_length=70),
        ),
    ]
