# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0009_auto_20170323_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='faculty',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('science', 'Science'), ('arts', 'Arts'), ('education', 'Education')], default='engineering', max_length=70),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
