# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0011_fbuser_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='major',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fb_mcbot.Major'),
        ),
    ]
