# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0014_auto_20170325_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='id',
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(choices=[('architecture', 'Architecture'), ('bioengineering', 'Bioengineering'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('computer_engineering', 'Computer Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('materials_engineering', 'Materials Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('mining_engineering', 'Mining Engineering'), ('software_engineering', 'Software Engineering')], default='architecture', max_length=70, primary_key=True, serialize=False),
        ),
    ]
