# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0015_auto_20170325_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(choices=[('comp_250', 'COMP 250'), ('ecse_428', 'ECSE 428'), ('ecse_322', 'ECSE 322'), ('ecse_330', 'ECSE 330'), ('math_363', 'MATH 363')], max_length=70, primary_key=True, serialize=False)),
                ('major', models.ManyToManyField(to='fb_mcbot.Major')),
            ],
        ),
    ]
