# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0016_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='major',
            new_name='majors',
        ),
        migrations.AddField(
            model_name='fbuser',
            name='courses',
            field=models.ManyToManyField(to='fb_mcbot.Course'),
        ),
    ]
