# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0009_auto_20170326_1729_squashed_0010_auto_20170326_1905'),
        ('fb_mcbot', '0017_auto_20170325_2221'),
    ]

    operations = [
    ]
