# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0002_auto_20170330_2021'),
        ('bot_mcgill', '0002_auto_20170330_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcgillevent',
            name='related_majors',
            field=models.ManyToManyField(to='fb_mcbot.Major'),
        ),
    ]
